### PR TITLE
add marko

### PR DESCRIPTION
**Pull request by argyleink**
it's close. i'll wrap it up unless you get some time to hack on it

### CODE REVIEW

**Comment by argyleink** [comment]
this was helpful http://markojs.com/docs/rollup/

**Comment by argyleink** [comment]
bah, i almost have this

**Comment by argyleink** [comment]
i noticed that Preact and Marko's .min files arent actually minified like React's and the others. Their bundles may not be the correct numbers since there's white space. Not sure why Rollup wont remove the whitespace from the bundle of these 2.

**Comment by jesseweed** [comment]
Preact specifically isn't minified because I disabled uglify ;)

That's just a temporary solution as I was too lazy to figure out why uglify was breaking things (https://github.com/jesseweed/build-recipes/blob/master/rollup/preact.js#L27).

To get minification for Marko, you'll need to either manually add uglify to the plugins, or just push the [common plugins](https://github.com/jesseweed/build-recipes/blob/master/rollup/_common.js) to the object (similar to [react](https://github.com/jesseweed/build-recipes/blob/master/rollup/react.js#L23)):

```
common.plugins.forEach((value, key) => {
  marko.plugins.push(value);
});
```

**Pull request merged**
